import { TracerProvider } from "@opentelemetry/api";
//#region src/errors.d.ts
/**
 * What went wrong:
 * - `missing_api_key`: no API key was passed and `BFL_API_KEY` is not set.
 * - `invalid_api_key`: the API rejected the key.
 * - `invalid_request`: the API rejected the input, or the `model` is unknown.
 * - `insufficient_credits`: the account has no credits left. Add credits, then start again.
 * - `rate_limited`: too many requests, or too many running jobs. Try again later.
 * - `server_error`: the API had an internal error. Try again later.
 * - `network_error`: the API could not be reached.
 * - `timeout`: the API did not answer in time (see `timeoutMs`).
 * - `unknown_error`: the API sent a reply the SDK does not understand.
 * - `invalid_job`: the job can't be checked: its `pollingUrl` is not a BFL host.
 * - `job_not_found`: no such job: the id is wrong, or the finished job was already deleted.
 */
type BflErrorCode = "missing_api_key" | "invalid_api_key" | "invalid_request" | "insufficient_credits" | "rate_limited" | "server_error" | "network_error" | "timeout" | "unknown_error" | "invalid_job" | "job_not_found";
/** An error from the SDK or the BFL API. `code` tells what went wrong. */
export declare class BflError extends Error {
  readonly name: "BflError";
  /** What went wrong. */
  readonly code: BflErrorCode;
  constructor(code: BflErrorCode, message: string, options?: ErrorOptions);
  /** `true` when the error is temporary: calling again later may work. */
  get retryable(): boolean;
  /**
   * `true` when `value` is a `BflError`. Unlike `instanceof`, it also works when the app has
   * several copies of the SDK installed.
   */
  static isInstance(value: unknown): value is BflError;
}
//#endregion
//#region src/job.d.ts
type JobError = {
  type: "error";
  message?: string;
} | {
  type: "request_moderated" | "content_moderated";
  reasons: string[];
};
type MediaFile = {
  /** Temporary link to the file. It expires 1 hour after the job ends: copy the file to keep it. */
  url: string;
  /** The mime type of the file */
  mimeType: string;
};
type BaseJobInput = {
  /** The model to use for generation */
  model: string;
  /** The prompt describing to the model what to do. */
  prompt: string;
  /**
   * Your own id for the end user who asked for the generation. 1 to 256 characters.
   */
  user?: string;
  /**
   * The model version. Default: `latest`, the current release.
   */
  version?: string;
  /**
   * These fields will be added directly to the request.
   * This should only be used for API fields not supported by the SDK.
   */
  extra?: Record<string, unknown>;
};
/**
 * A media generation job.
 */
type Job<JobInput extends BaseJobInput = BaseJobInput> = {
  /** The ID of the job. */
  readonly id: string;
  /** The input the job was started with. */
  readonly input: JobInput;
  /** When the job was started, in ms since epoch. */
  readonly startedAt: number;
  /** The cost, in credits. 1 credit = 1 US cent. */
  readonly cost?: number;
} & ({
  readonly status: "in_progress";
  /** The URL that can be used to check the status of a Job */
  readonly pollingUrl: string;
  /** A more granular status while the request is processing: `Pending` or `Generating`. */
  readonly processingStatus?: string;
  /** The progress of the Job */
  readonly progress?: number;
} | {
  readonly status: "ready";
  /** The media generated by the Job. */
  readonly media: MediaFile;
} | {
  readonly status: "failed";
  /** The error describing why the Job failed */
  readonly error: JobError;
});
/** A job which is still processing. */
type InProgressJob<JobInput extends BaseJobInput = BaseJobInput> = Extract<Job<JobInput>, {
  status: "in_progress";
}>;
/** A job that finished successfully. */
type ReadyJob<JobInput extends BaseJobInput = BaseJobInput> = Extract<Job<JobInput>, {
  status: "ready";
}>;
/** A job that failed. */
type FailedJob<JobInput extends BaseJobInput = BaseJobInput> = Extract<Job<JobInput>, {
  status: "failed";
}>;
//#endregion
//#region src/hooks.d.ts
/**
 * Hooks for executing code at various points in a Job's lifecycle.
 * Register them with `bfl.videos.registerHooks`. Every hook is optional.
 *
 * The SDK runs all registered hooks at the same time and waits for them before it returns.
 * Errors thrown by a hook are ignored: they never fail the SDK call or stop the other hooks.
 *
 * @example
 * ```ts
 * bfl.videos.registerHooks({
 *   onJobProgress: (job) => progressBar.update(job.progress ?? 0),
 *   onJobReady: (job) => console.log('Video ready:', job.media.url),
 * })
 * ```
 */
type JobHooks<Input extends BaseJobInput = BaseJobInput> = {
  /**
   * Called when a job could not be started, before the error is thrown.
   *
   * @param input - The input the job was started with
   * @param err - The error that is about to be thrown
   * @param startedAt - When the SDK started sending the job, in ms since epoch
   */
  onSubmitFailed?(input: Input, err: BflError, startedAt: number): void | Promise<void>;
  /**
   * Called when the job is ready.
   *
   * @param job - The ready job
   */
  onJobReady?(job: ReadyJob<Input>): void | Promise<void>;
  /**
   * Called when the job failed, e.g. blocked by moderation.
   *
   * @param job - The failed job
   */
  onJobFailed?(job: FailedJob<Input>): void | Promise<void>;
  /**
   * Called when a check finds the running job's `progress` or `processingStatus` changed, e.g. to
   * show `job.progress`.
   *
   * @param job - The running job
   */
  onJobProgress?(job: InProgressJob<Input>): void | Promise<void>;
};
//#endregion
//#region src/http.d.ts
/** Options for one call. */
type HttpRequestOptions = {
  /** How long to wait for the API, in ms. Default: 30 000 (30 s). `Infinity` means no timeout. */
  timeoutMs?: number;
  /**
   * Cancels the call. The call then throws the signal's reason (an `AbortError` by default),
   * not a `BflError`.
   */
  signal?: AbortSignal;
};
declare class HttpClient {
  #private;
  constructor(config: {
    apiKey: string;
    host: string;
    fetch: typeof fetch;
  });
  /**
   * Allow get queries to a custom URL for polling.
   * This will make sure the URL is safe to prevent sending the API key to untrusted hosts.
   */
  getCustomUrl<Res>(url: string, options?: HttpRequestOptions): Promise<Res>;
  post<Res>(path: string, body?: Record<string, unknown>, options?: HttpRequestOptions): Promise<Res>;
  request<Res>(method: RequestInit["method"], url: string, body?: Record<string, unknown>, options?: HttpRequestOptions): Promise<Res>;
}
//#endregion
//#region src/resources/videos/models/video_model.d.ts
/** The video models this SDK supports. */
type VideoModelId = "flux3";
//#endregion
//#region src/resources/videos.d.ts
/**
 * Base input for video generation jobs
 */
type VideoInput = BaseJobInput & {
  model: VideoModelId;
  /** The prompt describing to the model what to do.
   * Check https://docs.bfl.ai/guides/prompting_video_text_to_video for guidance.
   */
  prompt: string;
  /**
   * The duration of the video in whole seconds. Supported range: 5 - 20.
   * Default: Automatically detected from the prompt.
   */
  duration?: number;
  /**
   * The resolution of the video: `hd`, or `fhd`, `qhd` or `uhd` for a higher resolution made by
   * upscaling. The exact size depends on the aspect ratio. Default: `hd`.
   */
  resolution?: "hd" | "fhd" | "qhd" | "uhd";
  /** The aspect ratio of the video. Default: `auto`, chosen from the prompt. */
  aspectRatio?: "auto" | "21:9" | "2:1" | "16:9" | "4:3" | "1:1" | "3:4" | "9:16" | "9:21";
  /** Generate audio with the video. Default: `true`. */
  audio?: boolean;
};
/** Input for creating a text to video generation Job. */
type VideoFromTextInput = VideoInput & {};
/** A video generation Job, as returned by {@link Videos.fromText} and {@link Videos.check}. */
type VideoJob = Job<VideoFromTextInput>;
/** Options for {@link Videos.wait}. */
type WaitOptions = {
  /** How long to pause between checks, in ms. Default: 5 000 (5 s). */
  intervalMs?: number;
  /**
   * Stops waiting. `wait` then throws the signal's reason (an `AbortError` by default), not a
   * `BflError`. Without it, `wait` has no time limit.
   */
  signal?: AbortSignal;
};
/** Module for generating videos.
 * Accessed with `new Bfl().videos`
 * Call {@link Videos.fromText} to generate a video from a prompt.
 **/
declare class Videos {
  #private;
  constructor(http: HttpClient);
  /**
   * Registers hooks the SDK calls for every video job of this client: when a job can't be
   * started, when a check finds its progress or status changed, and when it is ready or failed.
   * Hooks run in {@link Videos.fromText} and {@link Videos.check}, so also in {@link Videos.wait}.
   *
   * @param hooks - The hooks to call. Every hook is optional.
   *
   * @example
   * ```ts
   * bfl.videos.registerHooks({
   *   onJobProgress: (job) => progressBar.update(job.progress ?? 0),
   * })
   * const job = await bfl.videos.wait(started)
   * ```
   */
  registerHooks(hooks: JobHooks<VideoFromTextInput>): void;
  /**
   * Starts generating a video from a text prompt.
   *
   * @param input - The settings for video generation
   * @param options - Options for configuring the HTTP request
   *
   * @returns The asynchronous job for the processing.
   * Save it, then pass it to {@link Videos.check} to get its status.
   * @throws {@link BflError} when the video can't be started, e.g. `invalid_request`,
   * `insufficient_credits` or `rate_limited`.
   *
   * @example
   * ```ts
   * const job = await bfl.videos.fromText({ model: 'flux3', prompt: 'A cat surfing a wave' })
   * await db.save(JSON.stringify(job))
   * ```
   */
  fromText(input: VideoFromTextInput, options?: HttpRequestOptions): Promise<InProgressJob<VideoFromTextInput>>;
  /**
   * Polls the API to check the status of a Job.
   * Only jobs with in_progress status are checked. Other jobs are returned unchanged.
   * The input Job will not be mutated, an updated Job object will be returned.
   * A job for which the processing failed is returned with status `failed`, not thrown.
   * Runs the registered {@link JobHooks} for the new state before returning.
   *
   * @param job - The Job to check
   * @param options - Options for configuring the HTTP request
   * @returns A copy of the Job, with the updated state
   * @throws {@link BflError} when the status can't be checked, e.g. `job_not_found` (BFL already
   * deleted the job), `invalid_job` or `network_error`.
   *
   * @example
   * ```ts
   * const job = await bfl.videos.check(JSON.parse(await db.load()))
   * if (job.status === 'ready') console.log(job.media.url)
   * ```
   */
  check<JobInput extends VideoInput>(job: Job<JobInput>, options?: HttpRequestOptions): Promise<Job<JobInput>>;
  /**
   * Waits for a Job to complete.
   * Thif will check right away, then every `intervalMs`, until it is ready or failed.
   * Checks that throw a retryable error are skipped. There is no time limit: pass a `signal`
   * to stop.
   *
   * @param job - The Job to wait for
   * @param options - The pause between checks, and a signal to stop
   * @returns The Job, ready or failed
   * @throws {@link BflError} when a check fails with an error that is not retryable, e.g.
   * `job_not_found` or `invalid_api_key`.
   *
   * @example
   * ```ts
   * const started = await bfl.videos.fromText({ model: 'flux3', prompt: 'A cat surfing a wave' })
   * const job = await bfl.videos.wait(started, { signal: AbortSignal.timeout(3_600_000) })
   * if (job.status === 'ready') console.log(job.media.url)
   * ```
   */
  wait<JobInput extends VideoInput>(job: Job<JobInput>, options?: WaitOptions): Promise<ReadyJob<JobInput> | FailedJob<JobInput>>;
}
//#endregion
//#region src/bfl.d.ts
/** Options for {@link Bfl}. */
type BflOptions = {
  /** Your BFL API key. Default: the `BFL_API_KEY` environment variable. */
  apiKey?: string;
  /** Send new jobs to the EU or US host. Default: `api.bfl.ai`. */
  region?: "eu" | "us";
  /** The `fetch` used for every request. Default: the global `fetch`. */
  fetch?: typeof fetch;
  /**
   * Each job gets a span, written through the app's OpenTelemetry setup.
   * Without one, nothing is recorded.
   */
  telemetry?: {
    /** Also record the prompt and the video URL on spans. Default: `false`. */
    recordContent?: boolean;
    /**
     * Write spans through this provider instead of the global one, e.g. when the runtime
     * registers its own global provider first (Supabase Edge, Deno with `OTEL_DENO`).
     * Default: the global provider.
     */
    tracerProvider?: TracerProvider;
  };
};
/**
 * Client for the Black Forest Labs API.
 *
 * @example
 * ```ts
 * const bfl = new Bfl() // reads BFL_API_KEY
 * const started = await bfl.videos.fromText({ model: 'flux3', prompt: 'A cat surfing a wave' })
 * // Save the job as JSON. Later, from any process:
 * const job = await bfl.videos.check(started)
 * if (job.status === 'ready') console.log(job.media.url)
 * ```
 */
export declare class Bfl {
  /** Generate videos. */
  readonly videos: Videos;
  /**
   * @throws {@link BflError} `missing_api_key` when no API key is passed and `BFL_API_KEY` is not set.
   */
  constructor(opts?: BflOptions);
}
//#endregion
export type { BflErrorCode, BflOptions, FailedJob, HttpRequestOptions, InProgressJob, Job, JobError, JobHooks, ReadyJob, VideoFromTextInput, VideoJob, WaitOptions };