export type JobError =
  | {
      type: 'error'
      message?: string
    }
  | { type: 'request_moderated' | 'content_moderated'; reasons: string[] }

export type MediaFile = {
  /** Temporary link to the file. It expires 1 hour after the job ends: copy the file to keep it. */
  url: string

  /** The mime type of the file */
  mimeType: string
}

export type BaseJobInput = {
  /** The model to use for generation */
  // INFO: This must be explicitly set and does not default to the latest model so that
  // upgrading the SDK doesn't switch the model without user consent
  model: string

  /** The prompt describing to the model what to do. */
  prompt: string

  /**
   * Your own id for the end user who asked for the generation. 1 to 256 characters.
   */
  user?: string

  /**
   * The model version. Default: `latest`, the current release.
   */
  version?: string

  /**
   * These fields will be added directly to the request.
   * This should only be used for API fields not supported by the SDK.
   */
  extra?: Record<string, unknown>
}

/**
 * A media generation job.
 */
export type Job<JobInput extends BaseJobInput = BaseJobInput> = {
  /** The ID of the job. */
  readonly id: string

  /** The input the job was started with. */
  readonly input: JobInput

  /** When the job was started, in ms since epoch. */
  readonly startedAt: number

  /** The cost, in credits. 1 credit = 1 US cent. */
  readonly cost?: number
} & (
  | {
      readonly status: 'in_progress'

      /** The URL that can be used to check the status of a Job */
      readonly pollingUrl: string

      /** A more granular status while the request is processing: `Pending` or `Generating`. */
      readonly processingStatus?: string

      /** The progress of the Job */
      readonly progress?: number
    }
  | {
      readonly status: 'ready'

      /** The media generated by the Job. */
      readonly media: MediaFile
    }
  | {
      readonly status: 'failed'

      /** The error describing why the Job failed */
      readonly error: JobError
    }
)

/** A job which is still processing. */
export type InProgressJob<JobInput extends BaseJobInput = BaseJobInput> = Extract<
  Job<JobInput>,
  { status: 'in_progress' }
>

/** A job that finished successfully. */
export type ReadyJob<JobInput extends BaseJobInput = BaseJobInput> = Extract<
  Job<JobInput>,
  { status: 'ready' }
>

/** A job that failed. */
export type FailedJob<JobInput extends BaseJobInput = BaseJobInput> = Extract<
  Job<JobInput>,
  { status: 'failed' }
>

export function advanceInProgress<JobInput extends BaseJobInput>(
  job: InProgressJob<JobInput>,
  fields: {
    processingStatus?: string
    cost?: number
    progress?: number
  },
): InProgressJob<JobInput> {
  return {
    ...job,
    ...fields,
  }
}

export function advanceToReady<JobInput extends BaseJobInput>(
  job: InProgressJob<JobInput>,
  fields: {
    media: MediaFile
    cost?: number
  },
): ReadyJob<JobInput> {
  return {
    ...sharedFields(job),
    status: 'ready',
    ...fields,
  }
}

export function advanceToFailed<JobInput extends BaseJobInput>(
  job: InProgressJob<JobInput>,
  fields: {
    cost?: number
    error: JobError
  },
): FailedJob<JobInput> {
  return {
    ...sharedFields(job),
    status: 'failed',
    ...fields,
  }
}

function sharedFields<JobInput extends BaseJobInput>(job: InProgressJob<JobInput>) {
  return { id: job.id, input: job.input, startedAt: job.startedAt }
}
